---

- hosts: mac

  tasks:
  - name: install apps via hombrew
    homebrew:
      name: "{{ item }}"
      state: latest
    with_items:
      - git
      - openssl
      - wget

    - name: install apps via homebrew cask
    homebrew_cask:
      name: iterm2
      state: installed